# Use a base image with Java 17 installed
FROM openjdk:17

# Copy the JAR file into the container at the specified path
ADD target/cicdimpl.jar /cicdimpl.jar

# Expose the port on which the Java application will run
EXPOSE 8080

# Specify the command to run your application
ENTRYPOINT ["java", "-jar", "/cicdimpl.jar"]